### ISSUE TITLE
Nextjs13 - ReferenceError: self is not defined

### ISSUE THREAD

**Issue by greengem** [arronhunt/highlightjs-copy#22]
I'm trying to integrate this into my nextjs13 site in a markdown file that renders blocks of rich text from my headless CMS, i'm using app router. This is probably do to my lack of knowledge with SSR but thought i'd ask here before giving up.

```
'use client'
import hljs from 'highlight.js';
import CopyButtonPlugin from 'highlightjs-copy';
hljs.addPlugin(new CopyButtonPlugin());
```
---
```
[BLOCKS.EMBEDDED_ENTRY]: (node) => {
                const entryId = node.data.target.sys.id;
                const entry = description.links.entries.block.find(e => e.sys.id === entryId);
                if (!entry) return null;
                const highlightedCode = hljs.highlight(entry.code, { language: entry.language }).value;
                return (
                    <div className='syntax-custom overflow-x-auto my-10'>
                        <p className="text-tiny uppercase font-bold mb-1 text-danger">{entry.language}</p>
                        <pre className='text-sm hljs-copy-wrapper'>
                            <code dangerouslySetInnerHTML={{ __html: highlightedCode }} />
                        </pre>
                    </div>
                );
            }
```
---
Error:

ReferenceError: self is not defined
    at eval (./lib/markdown.tsx:34:64)
    at (ssr)/./lib/markdown.tsx (/folder/.next/server/app/projects/[slug]/page.js:226:1)
    at __webpack_require__ (/folder/.next/server/webpack-runtime.js:33:43)
null

**Comment by Cody-W-Tucker** [comment]
Here's my CodeRending component, Nextjs 13.

```
'use client'
import 'highlight.js/styles/felipec.css'
import 'highlightjs-copy/dist/highlightjs-copy.min.css'

import hljs from 'highlight.js'
import CopyButtonPlugin from 'highlightjs-copy'
import { useEffect, useRef } from 'react'

let isCopyPluginAdded = false

export const CodeRendering = ({ children, language }) => {
  const codeRef = useRef<HTMLElement | null>(null)
  const prevChildrenRef = useRef(null)
  const prevLanguageRef = useRef(null)

  useEffect(() => {
    if (!isCopyPluginAdded) {
      hljs.addPlugin(new CopyButtonPlugin())
      isCopyPluginAdded = true
    }
    if (
      codeRef.current &&
      (children !== prevChildrenRef.current ||
        language !== prevLanguageRef.current)
    ) {
      hljs.highlightElement(codeRef.current)
      prevChildrenRef.current = children
      prevLanguageRef.current = language
    }
  }, [children, language])

  return (
    <pre className="hljs hljs-copy-wrapper ring-1 ring-gray-200 dark:ring-gray-800">
      <code
        ref={codeRef}
        className={`language-${language} whitespace-pre-wrap break-words`}
      >
        {children}
      </code>
    </pre>
  )
}
```
